// <auto-generated />
using System;
using AutoStrada.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoStrada.API.Data
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220310054729_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("AutoStrada.ENT.Product", b =>
                {
                    b.Property<int>("CodeProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodeSupplier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateFabrication")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateValidity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("CodeProduct");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            CodeProduct = 1,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 87, DateTimeKind.Local).AddTicks(3944),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 89, DateTimeKind.Local).AddTicks(59),
                            Description = "Aceite de bacalao",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 2,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1016),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1030),
                            Description = "jabon de cocina",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 3,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1105),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1106),
                            Description = "Leche Pasteurizada Entera",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 4,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1112),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1113),
                            Description = "Azúcar Blanca",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 5,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1118),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1119),
                            Description = "Atún en Lata",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 6,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1129),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1130),
                            Description = "Crema de cebolla",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 7,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1133),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1134),
                            Description = "Espinacas precocidas",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 8,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1136),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1137),
                            Description = "Guantes eterna",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 9,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1140),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1141),
                            Description = "Esponjilla Brillamas",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 10,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1145),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1146),
                            Description = "Lustrador de botas",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 11,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1149),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1150),
                            Description = "Bolsas Resellables",
                            State = true
                        },
                        new
                        {
                            CodeProduct = 12,
                            CodeSupplier = 1,
                            DateFabrication = new DateTime(2022, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1152),
                            DateValidity = new DateTime(2023, 3, 10, 0, 47, 29, 90, DateTimeKind.Local).AddTicks(1153),
                            Description = "Papel Absorvente",
                            State = true
                        });
                });

            modelBuilder.Entity("AutoStrada.ENT.Supplier", b =>
                {
                    b.Property<int>("CodeSupplier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionSupplier")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelephoneSupplier")
                        .HasColumnType("TEXT");

                    b.HasKey("CodeSupplier");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            CodeSupplier = 1,
                            DescriptionSupplier = "Superbodega del rincon",
                            Status = true,
                            TelephoneSupplier = "3123061932"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
